Pytorch is used for machine leaning and deep learning

What is deep learning?
It is a subset of machine learning, turning data (images, text) into numbers and finding patterns.

In [611]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Now that we have imported the nessacary libraries, we can begin with coding

**We will first start with tensor which is a way to represent data**

In [615]:
#First kind of tensor is a scalar

scalar = torch.tensor(7)
print(scalar)

tensor(7)


A scalar has no dimenstions therefore it outputs only one number

In [618]:
print(scalar.ndim)

0


In [620]:
# Get tensor back as Python int
print(scalar.item())

7


In [622]:
# The other thing is a vector
vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [624]:
print(vector.ndim)

1


So a basic idea of how many dimensions does a vector has is just to count the number square brackets in the tensor

In [627]:
print(vector.shape)

torch.Size([2])


vector.shape tells us how many elements are there in the vector

**Now lets explore a Matrix**

In [631]:
matrix = torch.tensor([[7,8], [9, 10]])
print(matrix)

tensor([[ 7,  8],
        [ 9, 10]])


In [633]:
matrix.ndim

2

In [635]:
matrix[1]

tensor([ 9, 10])

In [637]:
matrix[0]

tensor([7, 8])

The above gives the positional vectors in the matrix

In [640]:
matrix.shape
# number of elements in each vector

torch.Size([2, 2])

**Now lets go over tensor**

In [643]:
tensor = torch.tensor([[[1,2,3],[2,5,4],[6,9,7]]])

In [645]:
tensor

tensor([[[1, 2, 3],
         [2, 5, 4],
         [6, 9, 7]]])

In [647]:
tensor.ndim


3

In [649]:
tensor.shape

torch.Size([1, 3, 3])

Now the shape confuses a bit but this simple says we have a one 3x3 matrix

**SO ABOVE WE HAVE LEARNED THE BASICS OF PYTORCH**


No the common nomanclature is to represents a matrix or a tensor use a whole capital letter word, 
where as use lower case variable name for scalar and vector

**Random tensors**

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

start with random numbes ---> look at data ---> update random numbers ---> look at data ---> update random numbers


In [655]:
# create a random tensor of size (3, 4)

random_tensor = torch.rand(3,4)

In [657]:
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

So we have 3 rows and 4 columns with random values

In [660]:
random_tensor.ndim


2

In [662]:
random_tensor.shape


torch.Size([3, 4])

In [664]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

By the above we can see we can turn anything into a tensor, for example an image

**Tensor of zeros and ones**


In [668]:
zeros = torch.zeros(size=(3,4))

In [670]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

With such zeros and ones we can mask anything

In [673]:
zeros * random_tensor


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Create a tensor of ones


In [676]:
ones = torch.ones(3,4)

In [678]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

We can also see the datatype of a tensor by using .dtype

In [681]:
ones.dtype


torch.float32

**Now lets create a range of tensors and tensor-like**

In [684]:
# Use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

This gives a range for values from 0 to 9 excluding 10

We can also put a step

In [688]:
one_to_ten = torch.arange(0,11,1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [690]:
# We can also create tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

 So .zeros_like made the tensor fill with zeroes but with the same range like the range in one_to_ten

**Tensor datatypes**
**Note**: Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning:
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device


In [694]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

The device is used because during a computation, one tensor might live on the GPU while the other lives on the CPU, computing them with throw and error

In [697]:
 # Converting the datatype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [699]:
# We can multiply two tensors of different datatype
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [701]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [703]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

**Getting information from tensors**

1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not no the right device - to get device a tensor, can use tensor.device

In [706]:
 # create a random tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])

In [708]:
# find out some detail of a tensor
print(some_tensor)
print(f'Datatype of tensor: (some_tensor.dtype)')
print(f'Shape of tensor: (some_tensor.shape)')
print(f'Device tensor is on: (some_tensor.device)')

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])
Datatype of tensor: (some_tensor.dtype)
Shape of tensor: (some_tensor.shape)
Device tensor is on: (some_tensor.device)


**Manupliating Tensors**

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix manupliation


In [711]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [713]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [715]:
# Substract 
tensor - 10

tensor([-9, -8, -7])

In [717]:
# We can also try Pytorch builtin functions
torch.mul(tensor, 10) # mul short for multiply

tensor([10, 20, 30])

In [719]:
torch.div(tensor, 2) # div short for division

tensor([0.5000, 1.0000, 1.5000])

In [721]:
torch.sub(tensor, 2) # sub short for substraction

tensor([-1,  0,  1])

****Matrix Multiplication****

There are two ways of matrix multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication need to satisfy:
1. The **inner dimensions** must match:
   * (3, 2) @ (3, 2) won't work
   * (2, 3) @ (3, 2) will work
2. The resulting matrix has the shape of the **outer dimension**:
   * (2, 3) @ (3, 2) -> (2, 2)
   * (3, 2) @ (2, 3) -> (3, 3)

In [724]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [726]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [728]:
# multiplying by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [730]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 669 μs, sys: 901 μs, total: 1.57 ms
Wall time: 1.42 ms


In [732]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 122 μs, sys: 73 μs, total: 195 μs
Wall time: 149 μs


tensor(14)

When we compare the hand written matrix mul code with 
the pytorch function it is clear torch cumputes it it much less time

***One of the most common errors in deep learning: Shape errors***

In [736]:
# Shapes for matrix multipication
tensor_A = torch.tensor([[1, 2], 
                         [3, 4], 
                         [5, 6]])

tensor_B = torch.tensor([[7,10], 
                        [8, 11], 
                        [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

**IMPORTANT # torch.mm is the same as torch.matmul (It's an alias)**

We can see we have a shape error

In [739]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

The inner n does not match, So here we can use **Transpose**

A **Tranpose** switches the axis or dimensions of a given tensor


In [741]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [742]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

With .T we get the transpose of tensor_B

In [744]:
# Now we can multiply tensor_A and tensor_B
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [749]:
#The matrix mm operation works when tensor_B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}')
print(f'Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match')
print('Output:\n')
output = torch.mm(tensor_A, tensor_B.T)
print(f'\nOutput shape: {output.shape} ')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:


Output shape: torch.Size([3, 3]) 


***MATRIX AGGREGATION**

**Finding the min, max, mean, sum, etc (tensor aggregation)**

In [752]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [754]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [756]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [758]:
# Find the mean
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

Finally we got the second most common type of error **datatype error**
we can resolve this by changing the datatype of the data

In [761]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [763]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

***Finding the positional min and max***

In [766]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [768]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position
# of target tensor where minimum value ouccurs
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [770]:
# Find the position in tensor that has the maximum value with argmax() -> returns index position
# of target tensor where maximum value ouccurs
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

***Reshaping, stacking, squeezing and unsqueezing tensors***

* Reshaping - reshapes an input tensor to a defined shape
* View - Returns a view of an input tensor of centain shape but keep the same memory as the     og tensor
* Stacking - combine multiple tensors on top of each other (stack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the inpout with dimensions permuted (swapped) in a certain way

In [773]:
# create a tensor
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [775]:
# Add a new dimension
x_reshaped = x.reshape(1 , 9) # we can reshape in mutiples of the max number of positions in the tensor
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [777]:
# change view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

When using .view changing z will the change x (because a view of a tensor shares the same memory as the original

In [780]:
# Stack tensors on top 
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9],
         [1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([4, 9]))

#### squeeze and unsqueeze

In [783]:
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [785]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape # removes all single dimensions removed

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

 ### Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy.


In [789]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [791]:
# Lets index on the new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [793]:
# lets index on the middle bracket (dim=1)
x[0,0]

tensor([1, 2, 3])

In [795]:
# lets index on the most inner bracket (last diminsion)
x[0][0][0]

tensor(1)

In [797]:
# challenge get the number 9
x[0][2][2]

tensor(9)

In [799]:
# We can also use ':' to select 'all' of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [801]:
# Get values of 0th and 1st dimension but only index 1 of the 2nd dimension
x[:,1,1]

tensor([5])

## Pytorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPym array, want in Pytorch tensor -> torch.from_numpy(ndarray)
* Pytorch tensor -> Numpy -> torch.Tensor.numpy()

In [805]:
  # Numpy array to tensor
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

when going from numpy to pytorch the default datatype is float64

In [808]:
# change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

When changing the value of the array the original values of the array will not change and this will reflect on the tensor

In [811]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [813]:
# change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

When changing the value of the tensor the original values of the tensor will not change and this will reflect on the array

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

'start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...'

to reduce the randomness in neural networks in pytorch comes the concept of a **random seed**

Essentially what the random seed does is 'flavour' the randomness

In [817]:
import torch

## create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1336, 0.9666, 0.9754, 0.8474],
        [0.8988, 0.1105, 0.4563, 0.9719],
        [0.3968, 0.1496, 0.4743, 0.9973]])
tensor([[0.4436, 0.9726, 0.5194, 0.5337],
        [0.7050, 0.3362, 0.7891, 0.1694],
        [0.1800, 0.7177, 0.6988, 0.5510]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [819]:
# Lets make some random but reproduceable tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Runnign tensors and Pytorch objects on the GPUs (and making faster computations)

GPU = faster computation on numbers, thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest - Use Jupyter for a free GPU 

### Check for GPU access with Pytorch

In [824]:
# Check for GPU access with pytorch
import torch
torch.cuda.is_available()

False